apiVersion: v1
kind: Pod
metadata:
  name: dual-container-pod
spec:
  containers:
    - name: httpd-container
      image: httpd
      ports:
        - containerPort: 80
    - name: busybox-container
      image: busybox:latest
      command: ["sleep", "3600"]
