apiVersion: v1
kind: Secret
metadata:
  name: golang-http-server-secret
data:
  # base64 encoding for the entire .env file ( it'll be mounted to the pod using volumes )
  # .env: REFUQUJBU0VfVVJMPSdUSElTX0lTX0RVTU1ZX0RCX1VSTCcKUE9SVD00MDAwCkNMSUVOVF9VUkw9IlRISVNfSVNfRFVNTVlfVVJMIgpBQ0NFU1NfU0VDUkVUPSJUSElTX0lTX0RVTU1ZX0FDQ0VTU19TRUNSRVQiCkFXU19TRUNSRVQ9J1RISVNfSVNfRFVNTVlfQVdTX1NFQ1JFVCc=
  # base64 encoding for postgres://username:password@localhost:5432/database
  DATABASE_URL: cG9zdGdyZXM6Ly91c2VybmFtZTpwYXNzd29yZEBsb2NhbGhvc3Q6NTQzMi9kYXRhYmFzZQ==
  # base64 encoding for rajmane84
  USERNAME: cmFqbWFuZTg0